make image dimensions divisible by two, which is a pytorch requirement
https://github.com/pytorch/pytorch/blob/master/aten/src/ATen/native/PixelShuffle.cpp#L46-L51

Prevents

    RuntimeError: pixel_unshuffle expects width to be divisible by downscale_factor, but input.size(-1)=613 is not divisible by 2